# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 477017cdd730632b0656f873b6cc8c1bc5f86e7974f05cb882727b412f76fb8b39f695f46dcfa6a4563ab38f5f995381a90d027ee55d49039bc3bcf1ba3cb4e0

test:
  secret_key_base: bf33680fa4606754cafd16906c80a770c035065753fed7acc8f7395cd4b6b38de3e0baa6f2b4a964e781a63f5a120c5004ae0f6a80e6590055aa9479fd81bcc6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
